### ISSUE TITLE
Manifest import doesn't support singular-style buildpack spec

### ISSUE THREAD

**Issue by TimHess** [vmware-tanzu/tanzu-toolkit-for-visual-studio#280]
Given a manifest like the following:

```yaml
---
applications:
- name: some-app-with-manifest
  memory: 512M
  buildpack: dotnetcore_buildpack
```

The extension produces an error like this:
![image](https://user-images.githubusercontent.com/3947063/157329049-78d0c955-3681-405e-a9e0-e0340e09f46f.png)

The extension should either respect the way the buildpack is specified, optionally converting to newer format, or provide a more user-friendly message
