### ISSUE TITLE
Avoid windows remote debugging error pop up if possible

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#319]
When trying to remotely debug a barebones `net6.0` sample web app that was pushed to windows, this error popped up:

![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/62c0f618-9aa7-4339-8ab1-1c6a42bb555a)

#### Importantly:
This didn't impact the ability to remotely stop the app at breakpoints in VS, so it might just be noisy at worst

App was initially pushed with this manifest (I think):
```
version: 1
applications:
- name: WebApplication1
  path: C:\Users\awoosnam\source\repos\WebApplication1\WebApplication1\publish
  stack: windows
  buildpack: binary_buildpack
  command: cmd /c .\WebApplication1 --urls=http://0.0.0.0:%PORT%
```

Here's the result of `cf create-app-manifest WebApplication1`:
```
---
applications:
- name: WebApplication1
  buildpacks:
  - binary_buildpack
  stack: windows
  routes:
  - route: WebApplication1.apps.longbeach.cf-app.com
    protocol: http1
  processes:
  - type: web
    instances: 1
    memory: 1024M
    disk_quota: 1024M
    command: cmd /c .\WebApplication1 --urls=http://0.0.0.0:%PORT%
    health-check-type: port
```
