### ISSUE TITLE
Backspace/Delete keys occasionally stop working in Visual Studio

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#349]
@TimHess (but not @atwoosnam) has been able to reproduce this by loading this manifest into the deployment dialog:

```
version: 1
applications:
- name: DartStorageRegression
  memory: 256M
  buildpacks:
  - https://github.com/cloudfoundry/apt-buildpack/releases/download/v0.2.11/apt-buildpack-cflinuxfs3-v0.2.11.zip
  - dotnet_core_buildpack
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_NOLOGO: 1
  health-check-type: process
  no-route: true 
  stack: cflinuxfs3
```

Let's take a look at this more so we can determine if this is a bug introduced by this extension or not.
